apiVersion: v1alpha1
kind: Setting
metadata:
  name: plugin-postSpeech-settings
spec:
  forms:
    - group: basic
      label: 基本设置
      formSchema:
        - $el: a
          attrs:
            href: "https://docs.lik.cc/"
            class: "py-4 block"
            target: "_blank"
            style:
              color: "#1890ff"
              fontSize: "0.875em"
              display: "flex"
              align-items: "center"
          children:
            - $el: span
              children: "查看 语音朗读 帮助文档"
            - $el: img
              attrs:
                src: "/plugins/bingeWatching/assets/static/img/link.svg"
                width: "14px"
                height: "14px"
                style:
                  margin-left: "4px"
        - $el: span
          children: "加入交流群"
        - $el: img
          attrs:
            src: "https://www.lik.cc/upload/iShot_2025-03-03_16.03.00.png"
            width: "100px"
            height: "120px"
            style:
              margin-left: "80px"
        - $formkit: checkbox
          label: 开启文章朗读
          name: enableSpeech
          id: enableSpeech
          key: enableSpeech
          value: true
          help: "关闭后不在注入朗读功能"
        - $formkit: text
          if: $get(enableSpeech).value == true
          label: 文章路由
          name: postURL
          id: postURL
          key: postURL
          value: "*/archives/*"
          help: "在符合url条件的网页执行文章摘要功能，通常清况下，绝大多数Halo网站使用默认配置即可，无需调整"
        - $formkit: attachment
          if: $get(enableSpeech).value == true
          label: CSS样式
          name: speechStyle
          id: speechStyle
          key: speechStyle
          value: "/plugins/postSpeech/assets/static/css/likcc-speech.css"
          help: "朗读CSS文件地址,能力有限设计不出来好看的UI、有能力的大佬欢迎修改。最好能提PR 谢谢！"
        - $formkit: range
          if: $get(enableSpeech).value == true
          name: speechAloud
          id: speechAloud
          key: speechAloud
          label: '朗读语速'
          value: 1.5
          min: 1
          step: 0.1
          max: 2
          help: $get(speechAloud).value
        - $formkit: select
          if: $get(enableSpeech).value == true
          name: position
          key: position
          id: position
          label: 注入位置
          sortable: true
          clearable: true
          searchable: true
          validation: required
          value: "right"
          placeholder: 请选择注入位置
          options:
            - label: 右
              value: right
            - label: 左
              value: left